ROCK = 'Rock'
SCISSORS = 'Scissors'
PAPER = 'Paper'
LIZZY = 'Lizzy'
SPOCK = 'Spock'

GESTURES = {
  ROCK: [SCISSORS, LIZZY],
  SCISSORS: [PAPER, LIZZY],
  PAPER: [ROCK, SPOCK],
  LIZZY: [SPOCK, PAPER],
  SPOCK: [SCISSORS, ROCK]
}